services:
  geogramint_cli:
    container_name: cli
    build: .
    command: tail -f /dev/null
#    command: python geogramint.py --help
    stdin_open: true
    tty: true
    env_file:
      - .env.docker
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:7.0.14-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    env_file:
      - .env.docker

volumes:
  dbdata:
