FROM python:3.10-slim

ENV GEOGRAMINT_APP_FOLDER=/usr/src/app
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir $GEOGRAMINT_APP_FOLDER
WORKDIR $GEOGRAMINT_APP_FOLDER

RUN pip install --upgrade pip
COPY requirements.txt $GEOGRAMINT_APP_FOLDER
RUN pip install -r requirements.txt


COPY . $GEOGRAMINT_APP_FOLDER
